In [50]:
import torch
from neuron.activation_functions import sigmoid
x = torch.ones(1, requires_grad=True);
x

tensor([1.], requires_grad=True)

### Toy example

In [37]:
y = x**3 + 0.1 * x**2 + 1.
y

tensor([2.1000], grad_fn=<AddBackward0>)

In [38]:
y.backward()

In [39]:
x.grad       # 3x^2 + 0.1 * 2x @ x=1. = 3.2

tensor([3.2000])

## Perceptron

In [51]:
x = torch.ones(1, requires_grad=True);

weight = 0.5
bias = 2.
z = weight * x + bias
z

tensor([2.5000], grad_fn=<AddBackward0>)

In [54]:
activation = torch.sigmoid(z)        # sigmoid(0.5x + 2)
activation

tensor([0.9241], grad_fn=<SigmoidBackward>)

In [55]:
activation.backward()

In [58]:
x.grad          # sigmoid(0.5x + 2) * (1 - sigmoid(0.5x + 2)) @ x = 1. = 

tensor([0.0351])

In [59]:
dact_dz = sigmoid(weight * 1. + bias) * (1 - sigmoid(weight * 1. + bias))
dz_dx = 0.5

In [61]:
dact_dz * dz_dx

0.03505185827255403